import Foundation

public enum NonlinearConstraintRelation: String, Codable, Sendable { case lessThanOrEqual = "<="; case greaterThanOrEqual = ">="; case equal = "=" }

public struct NonlinearConstraint: Codable, Equatable, Sendable {
    public let name: String; public let expression: String; public let relation: NonlinearConstraintRelation; public let rhs: Double
    public init(name: String, expression: String, relation: NonlinearConstraintRelation, rhs: Double) { self.name=name;self.expression=expression;self.relation=relation;self.rhs=rhs }
}

public struct NonlinearProgram: Codable, Equatable, Sendable {
    public let title: String; public let sense: ObjectiveSense; public let objectiveExpression: String
    public let variableNames: [String]; public let lowerBounds: [Double?]; public let upperBounds: [Double?]
    public let constraints: [NonlinearConstraint]; public let normalizedStrictInequalities: Bool
    public init(title:String,sense:ObjectiveSense,objectiveExpression:String,variableNames:[String],lowerBounds:[Double?],upperBounds:[Double?],constraints:[NonlinearConstraint],normalizedStrictInequalities:Bool=false){self.title=title;self.sense=sense;self.objectiveExpression=objectiveExpression;self.variableNames=variableNames;self.lowerBounds=lowerBounds;self.upperBounds=upperBounds;self.constraints=constraints;self.normalizedStrictInequalities=normalizedStrictInequalities}
}

public struct NonlinearConstraintEvaluation: Codable, Equatable, Sendable { public let name:String;public let value:Double;public let relation:NonlinearConstraintRelation;public let rhs:Double;public let violation:Double }
public struct NonlinearProgramSolution: Codable, Equatable, Sendable { public let objectiveValue:Double;public let variableValues:[String:Double];public let constraintEvaluations:[NonlinearConstraintEvaluation];public let maximumViolation:Double;public let iterations:Int }
public struct NonlinearProgramSolutionDocument: Codable, Equatable, Sendable { public let backend:SolverRunMetadata;public let model:NonlinearProgram;public let solution:NonlinearProgramSolution }
public struct NonlinearProgramValidationDocument: Codable, Equatable, Sendable { public let backend:SolverBackendKind;public let isValid:Bool;public let diagnostics:[ValidationDiagnostic];public init(backend:SolverBackendKind,diagnostics:[ValidationDiagnostic]){self.backend=backend;self.isValid = !diagnostics.contains{$0.severity == .error};self.diagnostics=diagnostics} }
public enum NonlinearProgrammingError:Error,CustomStringConvertible{case unsupportedFormat;case invalidModel(String);case noConvergedSolution;public var description:String{switch self{case .unsupportedFormat:"Unsupported nonlinear-programming format";case .invalidModel(let x):"Invalid nonlinear program: \(x)";case .noConvergedSolution:"Native nonlinear solver did not find a sufficiently feasible solution"}}}

public enum WinQSBNonlinearProgrammingParser {
    public static func parse(from data:Data)throws->NonlinearProgram{
        guard let text=data.legacyLatin1String else{throw NonlinearProgrammingError.unsupportedFormat}
        let rows=text.replacingOccurrences(of:"\r\n",with:"\n").replacingOccurrences(of:"\r",with:"\n").split(separator:"\n",omittingEmptySubsequences:true).map{$0.split(separator:"\t",omittingEmptySubsequences:false).map{String($0).trimmingCharacters(in:.whitespacesAndNewlines)}}
        guard let metadata=rows.first,metadata.count>=4,metadata[0]=="NLP",let n=Int(metadata[2].trimmingCharacters(in:.whitespaces)),let m=Int(metadata[3].trimmingCharacters(in:.whitespaces)),rows.count>=3+m+n,rows[2].count>=2 else{throw NonlinearProgrammingError.unsupportedFormat}
        let variableRows=Array(rows.suffix(n)),names=variableRows.map{$0[0]}
        var lowers:[Double?]=[],uppers:[Double?]=[]
        for row in variableRows{let value=row.dropFirst().joined(separator:" ");lowers.append(try parseBound(value,marker:">="));uppers.append(try parseBound(value,marker:"<="))}
        let sense:ObjectiveSense
        if rows[2][0].caseInsensitiveCompare("Minimize") == .orderedSame{sense = .minimize}else if rows[2][0].caseInsensitiveCompare("Maximize") == .orderedSame{sense = .maximize}else{throw NonlinearProgrammingError.unsupportedFormat}
        var normalized=false
        let constraints=try (0..<m).map{index->NonlinearConstraint in
            let row=rows[3+index];guard row.count>=2 else{throw NonlinearProgrammingError.unsupportedFormat};let raw=row[1]
            let marker:String
            if raw.contains("<="){marker="<="}else if raw.contains(">="){marker=">="}else if raw.contains("<"){marker="<";normalized=true}else if raw.contains(">"){marker=">";normalized=true}else if raw.contains("="){marker="="}else{throw NonlinearProgrammingError.unsupportedFormat}
            let parts=raw.components(separatedBy:marker);guard parts.count==2,let rhs=Double(parts[1]) else{throw NonlinearProgrammingError.unsupportedFormat}
            let relation:NonlinearConstraintRelation = marker == "=" ? .equal : (marker.contains("<") ? .lessThanOrEqual:.greaterThanOrEqual)
            return NonlinearConstraint(name:row[0],expression:parts[0],relation:relation,rhs:rhs)
        }
        let model=NonlinearProgram(title:metadata[1],sense:sense,objectiveExpression:rows[2][1],variableNames:names,lowerBounds:lowers,upperBounds:uppers,constraints:constraints,normalizedStrictInequalities:normalized)
        try NonlinearProgramValidator.validate(model);return model
    }
    private static func parseBound(_ text:String,marker:String)throws->Double?{guard let range=text.range(of:marker)else{return nil};let raw=text[range.upperBound...].split(separator:",").first.map{String($0).trimmingCharacters(in:.whitespaces)} ?? "";if raw.isEmpty||raw.lowercased()=="m"{return nil};guard let value=Double(raw),value.isFinite else{throw NonlinearProgrammingError.invalidModel("Invalid bound '\(raw)'")};return value}
}

private indirect enum NLPExpression {
    case constant(Double),variable(Int),add(NLPExpression,NLPExpression),subtract(NLPExpression,NLPExpression),multiply(NLPExpression,NLPExpression),divide(NLPExpression,NLPExpression),power(NLPExpression,NLPExpression),negate(NLPExpression),function(String,NLPExpression)
    struct Dual { var value:Double;var gradient:[Double] }
    func evaluate(_ x:[Double])->Dual{
        func binary(_ lhs:NLPExpression,_ rhs:NLPExpression,_ body:(Dual,Dual)->Dual)->Dual{body(lhs.evaluate(x),rhs.evaluate(x))}
        switch self{
        case .constant(let v):return Dual(value:v,gradient:Array(repeating:0,count:x.count))
        case .variable(let i):var g=Array(repeating:0.0,count:x.count);g[i]=1;return Dual(value:x[i],gradient:g)
        case .add(let a,let b):return binary(a,b){Dual(value:$0.value+$1.value,gradient:zip($0.gradient,$1.gradient).map(+))}
        case .subtract(let a,let b):return binary(a,b){Dual(value:$0.value-$1.value,gradient:zip($0.gradient,$1.gradient).map(-))}
        case .multiply(let a,let b):return binary(a,b){u,v in Dual(value:u.value*v.value,gradient:zip(u.gradient,v.gradient).map{$0*v.value+$1*u.value})}
        case .divide(let a,let b):return binary(a,b){u,v in let d=v.value*v.value;return Dual(value:u.value/v.value,gradient:zip(u.gradient,v.gradient).map{($0*v.value-$1*u.value)/d})}
        case .power(let a,let b):return binary(a,b){u,v in let value=Foundation.pow(u.value,v.value);let logTerm=u.value>0 ? log(u.value):0;return Dual(value:value,gradient:zip(u.gradient,v.gradient).map{value*($1*logTerm+(u.value == 0 ? 0:v.value*$0/u.value))})}
        case .negate(let a):let u=a.evaluate(x);return Dual(value:-u.value,gradient:u.gradient.map { -$0 })
        case .function(let name,let a):let u=a.evaluate(x);let pair:(Double,Double)=switch name{case "exp":(exp(u.value),exp(u.value));case "log":(log(u.value),1/u.value);case "sqrt":(sqrt(u.value),1/(2*sqrt(u.value)));case "sin":(sin(u.value),cos(u.value));case "cos":(cos(u.value),-sin(u.value));default:(.nan,.nan)};return Dual(value:pair.0,gradient:u.gradient.map{$0*pair.1})
        }
    }
}

private struct NLPExpressionParser {
    private enum Token:Equatable{case number(Double),identifier(String),plus,minus,star,slash,power,left,right,end}
    private var tokens:[Token];private var index=0;private let names:[String]
    init(_ source:String,names:[String])throws{self.names=names;self.tokens=try Self.tokenize(source)+[.end]}
    mutating func parse()throws->NLPExpression{let expression=try sum();guard tokens[index] == .end else{throw NonlinearProgrammingError.invalidModel("Unexpected token in expression")};return expression}
    private mutating func sum()throws->NLPExpression{var value=try product();while true{if take(.plus){value = .add(value,try product())}else if take(.minus){value = .subtract(value,try product())}else{return value}}}
    private mutating func product()throws->NLPExpression{var value=try unary();while true{if take(.star){value = .multiply(value,try unary())}else if take(.slash){value = .divide(value,try unary())}else if startsPrimary(tokens[index]){value = .multiply(value,try unary())}else{return value}}}
    private mutating func unary()throws->NLPExpression{if take(.plus){return try unary()};if take(.minus){return .negate(try unary())};return try exponent()}
    private mutating func exponent()throws->NLPExpression{var value=try primary();if take(.power){value = .power(value,try unary())};return value}
    private mutating func primary()throws->NLPExpression{let token=tokens[index];index+=1;switch token{case .number(let v):return .constant(v);case .identifier(let raw):if take(.left){let arg=try sum();guard take(.right)else{throw NonlinearProgrammingError.invalidModel("Missing closing parenthesis")};let name=raw.lowercased();guard ["exp","log","sqrt","sin","cos"].contains(name)else{throw NonlinearProgrammingError.invalidModel("Unsupported function \(raw)")};return .function(name,arg)};guard let i=names.firstIndex(where:{$0.caseInsensitiveCompare(raw) == .orderedSame})else{throw NonlinearProgrammingError.invalidModel("Unknown variable \(raw)")};return .variable(i);case .left:let value=try sum();guard take(.right)else{throw NonlinearProgrammingError.invalidModel("Missing closing parenthesis")};return value;default:throw NonlinearProgrammingError.invalidModel("Expected expression value")}}
    private mutating func take(_ token:Token)->Bool{if tokens[index]==token{index+=1;return true};return false}
    private func startsPrimary(_ token:Token)->Bool{switch token{case .number,.identifier,.left:return true;default:return false}}
    private static func tokenize(_ source:String)throws->[Token]{var result:[Token]=[],i=source.startIndex;while i<source.endIndex{let c=source[i];if c.isWhitespace{i=source.index(after:i);continue};switch c{case "+":result.append(.plus);i=source.index(after:i);case "-":result.append(.minus);i=source.index(after:i);case "*":result.append(.star);i=source.index(after:i);case "/":result.append(.slash);i=source.index(after:i);case "^":result.append(.power);i=source.index(after:i);case "(":result.append(.left);i=source.index(after:i);case ")":result.append(.right);i=source.index(after:i);default:if c.isNumber||c=="."{let start=i;i=source.index(after:i);while i<source.endIndex&&(source[i].isNumber||source[i]=="."||source[i]=="E"||source[i]=="e"||((source[i]=="+"||source[i]=="-")&&source[source.index(before:i)].lowercased()=="e")){i=source.index(after:i)};guard let v=Double(source[start..<i])else{throw NonlinearProgrammingError.invalidModel("Invalid number")};result.append(.number(v))}else if c.isLetter||c=="_"{let start=i;i=source.index(after:i);while i<source.endIndex&&(source[i].isLetter||source[i].isNumber||source[i]=="_"){i=source.index(after:i)};result.append(.identifier(String(source[start..<i])))}else{throw NonlinearProgrammingError.invalidModel("Unsupported character \(c)")}}};return result}
}

public enum NonlinearProgramValidator {
    public static func diagnostics(for model:NonlinearProgram)->[ValidationDiagnostic]{var result:[ValidationDiagnostic]=[];let n=model.variableNames.count;if n==0||Set(model.variableNames.map{$0.lowercased()}).count != n||model.lowerBounds.count != n||model.upperBounds.count != n{result.append(diagnostic("dimension","Variables and bound dimensions must agree and names must be unique.","model"))};for i in 0..<min(n,model.lowerBounds.count){if let l=model.lowerBounds[i],let u=model.upperBounds[i],l>u{result.append(diagnostic("bounds","Lower bound exceeds upper bound.","model.lowerBounds[\(i)]"))}};do{var parser=try NLPExpressionParser(model.objectiveExpression,names:model.variableNames);_ = try parser.parse();for c in model.constraints{var p=try NLPExpressionParser(c.expression,names:model.variableNames);_ = try p.parse();if !c.rhs.isFinite{throw NonlinearProgrammingError.invalidModel("Nonfinite RHS")}}}catch{result.append(diagnostic("expression",String(describing:error),"model"))};if model.variableNames.count>4{result.append(diagnostic("scale","Native nonlinear solving supports at most four variables.","model.variableNames"))};if result.isEmpty{if model.normalizedStrictInequalities{result.append(ValidationDiagnostic(severity:.warning,code:"nlp.strict.normalized",message:"Strict legacy inequalities are solved as non-strict boundaries."))};result.append(ValidationDiagnostic(severity:.info,code:"nlp.valid",message:"Nonlinear program is valid"))};return result}
    public static func validate(_ model:NonlinearProgram)throws{if let x=diagnostics(for:model).first(where:{$0.severity == .error}){throw NonlinearProgrammingError.invalidModel(x.message)}}
    private static func diagnostic(_ code:String,_ message:String,_ path:String)->ValidationDiagnostic{ValidationDiagnostic(severity:.error,code:"nlp.\(code)",message:message,path:path)}
}

public enum NonlinearProgrammingSolver {
    private struct CompiledConstraint{let model:NonlinearConstraint;let expression:NLPExpression}
    public static func solve(_ model:NonlinearProgram)throws->NonlinearProgramSolution{try NonlinearProgramValidator.validate(model);var p=try NLPExpressionParser(model.objectiveExpression,names:model.variableNames);let objective=try p.parse();let constraints=try model.constraints.map{c->CompiledConstraint in var parser=try NLPExpressionParser(c.expression,names:model.variableNames);return CompiledConstraint(model:c,expression:try parser.parse())};var best:(x:[Double],objective:Double,violation:Double,iterations:Int)?=twoVariableEqualitySearch(model:model,objective:objective,constraints:constraints)
        if best == nil{for start in startPoints(model){var x=start,total=0;for rho in [1.0,1_000.0,1_000_000.0,1_000_000_000.0]{let optimized=optimize(x,model:model,objective:objective,constraints:constraints,rho:rho);x=optimized.x;total+=optimized.iterations};let raw=objective.evaluate(x).value,violation=maximumViolation(x,constraints);if best == nil||violation<best!.violation-1e-7||(violation<1e-5&&best!.violation<1e-5&&better(raw,best!.objective,model.sense)){best=(x,raw,violation,total)}}}
        guard let best,best.violation<1e-4 else{throw NonlinearProgrammingError.noConvergedSolution};let evaluations=constraints.map{c in let value=c.expression.evaluate(best.x).value;return NonlinearConstraintEvaluation(name:c.model.name,value:value,relation:c.model.relation,rhs:c.model.rhs,violation:violation(value,c.model))};return NonlinearProgramSolution(objectiveValue:best.objective,variableValues:Dictionary(uniqueKeysWithValues:zip(model.variableNames,best.x)),constraintEvaluations:evaluations,maximumViolation:best.violation,iterations:best.iterations)}
    private static func optimize(_ start:[Double],model:NonlinearProgram,objective:NLPExpression,constraints:[CompiledConstraint],rho:Double)->(x:[Double],iterations:Int){var x=start;for iteration in 0..<500{let current=penalized(x,model,objective,constraints,rho);let norm=sqrt(current.gradient.reduce(0){$0+$1*$1});if !current.value.isFinite || !norm.isFinite{return(x,iteration)};if norm<1e-9{return(x,iteration)};var step=min(1.0,1/norm),accepted=false;for _ in 0..<40{var candidate=zip(x,current.gradient).map{$0-$1*step};project(&candidate,model);let next=penalized(candidate,model,objective,constraints,rho);if next.value<current.value-1e-4*step*norm*norm{x=candidate;accepted=true;break};step*=0.5};if !accepted{return(x,iteration)}};return(x,500)}
    private static func penalized(_ x:[Double],_ model:NonlinearProgram,_ objective:NLPExpression,_ constraints:[CompiledConstraint],_ rho:Double)->NLPExpression.Dual{var result=objective.evaluate(x);if model.sense == .maximize{result.value = -result.value;result.gradient=result.gradient.map { -$0 }};for c in constraints{let d=c.expression.evaluate(x),v=d.value-c.model.rhs;let signed:Double;switch c.model.relation{case .equal:signed=v;case .lessThanOrEqual:signed=max(0,v);case .greaterThanOrEqual:signed=min(0,v)};if signed != 0{result.value += rho*signed*signed;let factor=2*rho*signed;result.gradient=zip(result.gradient,d.gradient).map{$0+factor*$1}}};return result}
    private static func startPoints(_ model:NonlinearProgram)->[[Double]]{let axes=model.variableNames.indices.map{i->[Double] in let l=model.lowerBounds[i] ?? -10,u=model.upperBounds[i] ?? 10;if abs(u-l)<1e-12{return[l]};return [l,(l+u)/2,u]};var result:[[Double]]=[[]];for axis in axes{result=result.flatMap{prefix in axis.map{prefix+[$0]}}};return result}
    private static func twoVariableEqualitySearch(model:NonlinearProgram,objective:NLPExpression,constraints:[CompiledConstraint])->(x:[Double],objective:Double,violation:Double,iterations:Int)?{guard model.variableNames.count==2,let equality=constraints.first(where:{$0.model.relation == .equal}),constraints.filter({$0.model.relation == .equal}).count==1,let lower0=model.lowerBounds[0],let upper0=model.upperBounds[0],let lower1=model.lowerBounds[1],let upper1=model.upperBounds[1]else{return nil};var range=(lower0,upper0),best:(x:[Double],objective:Double)?;var evaluations=0
        for _ in 0..<6{let steps=300,step=(range.1-range.0)/Double(steps);for i in 0...steps{let x0=range.0+Double(i)*step;let roots=equalityRoots(x0:x0,lower:lower1,upper:upper1,equality:equality);for x1 in roots{let point=[x0,x1];evaluations+=1;guard maximumViolation(point,constraints)<1e-7 else{continue};let value=objective.evaluate(point).value;if best==nil||better(value,best!.objective,model.sense){best=(point,value)}}};guard let current=best else{return nil};range=(max(lower0,current.x[0]-step*2),min(upper0,current.x[0]+step*2))}
        guard let best else{return nil};return(best.x,best.objective,maximumViolation(best.x,constraints),evaluations)}
    private static func equalityRoots(x0:Double,lower:Double,upper:Double,equality:CompiledConstraint)->[Double]{let segments=80,step=(upper-lower)/Double(segments);func value(_ x1:Double)->Double{equality.expression.evaluate([x0,x1]).value-equality.model.rhs};var roots:[Double]=[],left=lower,leftValue=value(left);for i in 1...segments{let right=lower+Double(i)*step,rightValue=value(right);if abs(leftValue)<1e-9{roots.append(left)};if leftValue*rightValue<0{var a=left,b=right,fa=leftValue;for _ in 0..<50{let mid=(a+b)/2,fm=value(mid);if fa*fm<=0{b=mid}else{a=mid;fa=fm}};roots.append((a+b)/2)};left=right;leftValue=rightValue};if abs(leftValue)<1e-9{roots.append(upper)};return roots}
    private static func project(_ x:inout[Double],_ model:NonlinearProgram){for i in x.indices{if let l=model.lowerBounds[i]{x[i]=max(x[i],l)};if let u=model.upperBounds[i]{x[i]=min(x[i],u)}}}
    private static func maximumViolation(_ x:[Double],_ constraints:[CompiledConstraint])->Double{constraints.map{violation($0.expression.evaluate(x).value,$0.model)}.max() ?? 0}
    private static func violation(_ value:Double,_ c:NonlinearConstraint)->Double{switch c.relation{case .equal:abs(value-c.rhs);case .lessThanOrEqual:max(0,value-c.rhs);case .greaterThanOrEqual:max(0,c.rhs-value)}}
    private static func better(_ x:Double,_ y:Double,_ sense:ObjectiveSense)->Bool{sense == .maximize ? x>y:y>x}
}

public protocol NonlinearProgrammingBackend:Sendable{var capabilities:SolverCapabilities{get};func validationReport(for model:NonlinearProgram)->ValidationReport;func solve(_ model:NonlinearProgram,options:SolverOptions)throws->NonlinearProgramSolution;func runMetadata(for model:NonlinearProgram)->SolverRunMetadata}
public extension NonlinearProgrammingBackend{func validationReport(for model:NonlinearProgram)->ValidationReport{ValidationReport(backend:capabilities.backendKind,diagnostics:NonlinearProgramValidator.diagnostics(for:model))};func solve(_ model:NonlinearProgram)throws->NonlinearProgramSolution{try solve(model,options:SolverOptions())};func solutionDocument(for model:NonlinearProgram,solution:NonlinearProgramSolution)->NonlinearProgramSolutionDocument{NonlinearProgramSolutionDocument(backend:runMetadata(for:model),model:model,solution:solution)}}
public struct NativeEducationalNonlinearProgrammingBackend:NonlinearProgrammingBackend{public init(){};public var capabilities:SolverCapabilities{SolverCapabilities(backendKind:.nativeEducational,solves:true,validates:true,exportsStructuredSolution:true,notes:["Deterministic multistart gradient optimization with progressive constraint penalties."])};public func solve(_ model:NonlinearProgram,options _:SolverOptions=SolverOptions())throws->NonlinearProgramSolution{try NonlinearProgrammingSolver.solve(model)};public func runMetadata(for model:NonlinearProgram)->SolverRunMetadata{SolverRunMetadata(backendKind:.nativeEducational,algorithm:"automaticDifferentiationMultistartPenalty",exactness:.approximate,notes:["Returns a numerically feasible local/global candidate for small fixtures; general global optimality is not guaranteed."]+(model.normalizedStrictInequalities ? ["Strict inequalities are normalized to non-strict boundaries."]:[]))}}
public struct ValidateOnlyNonlinearProgrammingBackend:NonlinearProgrammingBackend{public init(){};public var capabilities:SolverCapabilities{SolverCapabilities(backendKind:.validateOnly,solves:false,validates:true,exportsStructuredSolution:false)};public func solve(_ model:NonlinearProgram,options _:SolverOptions=SolverOptions())throws->NonlinearProgramSolution{throw NonlinearProgrammingError.invalidModel("validateOnly backend does not solve nonlinear programs")};public func runMetadata(for _:NonlinearProgram)->SolverRunMetadata{SolverRunMetadata(backendKind:.validateOnly,algorithm:"validationOnly",exactness:.exact)}}
public enum NonlinearProgrammingBackends{public static func backend(for kind:SolverBackendKind)->(any NonlinearProgrammingBackend)?{switch kind{case .nativeEducational:NativeEducationalNonlinearProgrammingBackend();case .validateOnly:ValidateOnlyNonlinearProgrammingBackend();case .externalHighPerformance:nil}}}
public enum NonlinearProgrammingJSON{public static func encodeModel(_ x:NonlinearProgram)throws->Data{try encoder.encode(x)};public static func decodeUncheckedModel(from x:Data)throws->NonlinearProgram{try JSONDecoder().decode(NonlinearProgram.self,from:x)};public static func decodeModel(from x:Data)throws->NonlinearProgram{let m=try decodeUncheckedModel(from:x);try NonlinearProgramValidator.validate(m);return m};public static func encodeSolution(_ x:NonlinearProgramSolutionDocument)throws->Data{try encoder.encode(x)};public static func decodeSolution(from x:Data)throws->NonlinearProgramSolutionDocument{try JSONDecoder().decode(NonlinearProgramSolutionDocument.self,from:x)};public static func encodeValidation(_ x:NonlinearProgramValidationDocument)throws->Data{try encoder.encode(x)};private static var encoder:JSONEncoder{let e=JSONEncoder();e.outputFormatting=[.prettyPrinted,.sortedKeys];return e}}
